input_features:
    -
        name: text
        type: text
        level: word
        encoder: rnn
        cell_type: lstm
        bidirectional: true
        num_layers: 1
        embedding_size: 16
        state_size: 64
        reduce_output: last
        preprocessing:
            word_format: space

output_features:
    -
        name: probs
        type: vector
        softmax: true
        num_fc_layers: 1
        fc_size: 64
        loss:
            type: softmax_cross_entropy
            confidence_penalty: 0
            robust_lambda: 0
            class_weights: 1
            class_similarities: null
            class_similarities_temperature: 0
            labels_smoothing: 0
            negative_samples: 0
            sampler: null
            distortion: 1
            unique: false
                
training:
    epochs: 25
    learning_rate: 0.01
    reduce_learning_rate_on_plateau: 5
    reduce_learning_rate_on_plateau_patience: 2
    reduce_learning_rate_on_plateau_rate: 0.5
    validation_measure: loss
    regularization_lambda: 0.0005

        